<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= PAGE_TITLE ?> - Nuit de l'info</title>
</head>
<body>

    <nav>
        <a href="/">Accueil</a>
        <a href="/contact.php">Nous contacter</a>
    </nav>

    <?php include('views/' . PAGE_CONTENT_FILE); ?>

</body>
</html>